name: Build and Release

on:
  push:
    tags:
    - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1
        
    - name: Build with MSBuild
      run: |
        msbuild /p:Configuration=Release /p:Platform="Any CPU" /t:Rebuild
        
    - name: Create ZIP archive
      run: |
        Compress-Archive -Path "bin/Release/ZZZConfigManager.exe" -DestinationPath "ZZZConfigManager.zip"
        
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: "ZZZConfigManager.zip"
